### ISSUE TITLE
I want to move the overlay image freely.

### ISSUE THREAD

**Issue by dongs0104** [guhungry/react-native-photo-manipulator#13]
I want to move the overlay image freely.

**Comment by guhungry** [comment]
Hi, what do you mean by move overlay image freely? is it rotate or position or anything else?

**Comment by dongs0104** [comment]
when I set up a watermark for image I want to select position freely for watermark on image.

**Comment by guhungry** [comment]
Is the https://github.com/guhungry/react-native-photo-manipulator/blob/master/README.md#overlay-image what you are looking for?
