### ISSUE TITLE
Add option to specify filetype

### ISSUE THREAD

**Issue by Jarred-Sumner** [guhungry/react-native-photo-manipulator#15]
I want to save images as PNGs instead of JPEGs, but the iOS code seems to hardcode the type to JPEG.

I'm going to fork it and modify it to fit my use case. Would you be fine with a PR that adds it as an option?

**Comment by guhungry** [comment]
@Jarred-Sumner Thanks, that would be great. Some Typescript declarations for mimeType might need to be `mimeType?: MimeType`
May be i'll add this to android too. I'm not sure if it'll break android or not.

**Comment by Jarred-Sumner** [comment]
i changed more stuff on my branch since this comment

it has WebP support on iOS now

but it adds a dependency on `SDWebImage` -- which might be undesirable

**Comment by guhungry** [comment]
Ok, thanks for the idea I'll do it myself then.
I'll fix the tests, add android support and document.

**Comment by guhungry** [comment]
This feature is included in 1.1.0.
Thanks @Jarred-Sumner
