### ISSUE TITLE
Choose Font family

### ISSUE THREAD

**Issue by Florent75** [guhungry/react-native-photo-manipulator#160]
Hi there,

It's a great tool and we have been having a lot of fun with it.

Would it be possible to choose the font family as an option for text ?

Regards

**Comment by guhungry** [comment]
Hi @Florent75 , I release this feature in version 1.2.4 🎉 🎉 🎉 

![image](https://user-images.githubusercontent.com/4032276/118373496-63b4e280-b5e1-11eb-9982-8641b198401a.png)

**Comment by Florent75** [comment]
Hi Guhungry,

So cool !! Sorry for the delay, but I am quite happy to use this new feature !

Thanks,

Regards
