### ISSUE TITLE
[Unhandled promise rejection: TypeError: null is not an object (evaluating 'RNPhotoManipulator.overlayImage')]

### ISSUE THREAD

**Issue by theianjohnson** [guhungry/react-native-photo-manipulator#165]
Trying to use this in an existing React Native (Expo) project and when I try to run this code I get the unhandled promise rejection - is there something else I need to be doing?

```
import PhotoManipulator from 'react-native-photo-manipulator';

const image = "https://unsplash.com/photos/qw6qQQyYQpo/download?force=true";
const overlay = "https://www.iconfinder.com/icons/1174949/download/png/128";
const position = { x: 5, y: 20 };

PhotoManipulator.overlayImage(image, overlay, position).then(path => {
    console.log(`Result image path: ${path}`);
});
```

**Comment by VityaSchel** [comment]
> From what I know Expo doesn't support Native Modules, right?
> 
> This library use native modules https://github.com/guhungry/android-photo-manipulator, https://github.com/guhungry/ios-photo-manipulator
> 
> Edit:
> This library doesn't support Expo due to this is a Native Modules library not pure javascript
> https://docs.expo.io/workflow/using-libraries/#determining-third-party-library-compatibility

Could you provide some alternatives to your module? https://docs.expo.dev/versions/v42.0.0/sdk/imagemanipulator/ only has 4 very basic methods, and I would like to use optimize method to compress images before sending it to my server.
