### ISSUE TITLE
What type of units are used to describe for position ?

### ISSUE THREAD

**Issue by dat39905** [guhungry/react-native-photo-manipulator#295]
For print texts into image, I see document describe point which represents a position (x, y) from top-left of the image. So what type unit of measurements for them when run on device? (dp, pt or px )

I asked because when i get x-axis coordinate and y-axis coordinate in a real device for print texts into the image, it seems to be the position after applied pretty much skewed.

**Comment by guhungry** [comment]
afasik it is pixel.
