### ISSUE TITLE
XCodeBuild modulemap not found

### ISSUE THREAD

**Issue by datoon83** [guhungry/react-native-photo-manipulator#311]
When building with xcodebuild I get the following issue:

fatal error: module map file
      '/Users/xcodeclub/Library/Developer/Xcode/DerivedData/carcloudapp-fpunvqnzmyqummgfroiwvewvqwdb/Build/Intermediates.noindex/ArchiveIntermediates/carcloudapp/BuildProductsPath/Release-iphoneos/WCPhotoManipulator/WCPhotoManipulator.modulemap'
      not found

"react": "16.13.1",
"react-native": "0.63.3",
"react-native-photo-manipulator": "^1.2.1"

Any advice on how to fix this issue?

**Comment by guhungry** [comment]
Can you try using solutions in https://github.com/facebook/react-native/issues/29605?

**Comment by thunderclap1030** [comment]
For Xcode : 12+
You specific option  `workspace` instead of `project` for resolve problem
Example :
 xcodebuild -showBuildSettings -workspace ./ios/ReactNative.xcworkspace
