### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): Error: height

### ISSUE THREAD

**Issue by master-css** [guhungry/react-native-photo-manipulator#324]
I am facing a error like :
Possible Unhandled Promise Rejection (id: 0): Error: height 

and i can't able to return a croped image path 

import React from 'react';
import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text, Image,ImageBackground
} from 'react-native';
import RNPhotoManipulator from 'react-native-photo-manipulator';

const image = "https://unsplash.com/photos/qw6qQQyYQpo/download?force=true";
const cropRegion = { x: 5, y: 30, height: 400, width: 250 };
const targetSize = { size: 200, width: 150 };

function Crop_img() {
   RNPhotoManipulator.crop(image, cropRegion, targetSize).then(path => {
        console.log(`Result image path: ${path}`);
    });
}

const Img=()=>{

  Crop_img();
  return (
   
    <Text>okk</Text>
    );
}

class App extends React.Component {

  render(){

    return ( 
      <View>
      <Text>Jenil Chavda</Text>
      <Img/>
      </View>

    );
  }
}

export default React.memo(App);

 const styles = StyleSheet.create(  
{  
   
   container: {
    flex: 1,
    backgroundColor: '#FBFCFC', //#FFFAFA

    flexDirection: 'column',alignItems: 'center',alignSelf: 'stretch', justifyContent:'space-around',
  },
  component: {
    backgroundColor: '#FFF', //#FFFAFA
    marginHorizontal:8,
    marginVertical:8,
  },
});

**Comment by guhungry** [comment]
const targetSize = { size: 200, width: 150 };
should be 
const targetSize = { **_height_**: 200, width: 150 };
