### ISSUE TITLE
Android 8.0.0 changes orientation of modified image

### ISSUE THREAD

**Issue by akrueger90** [guhungry/react-native-photo-manipulator#343]
Hello, 
I have a Samsung Galaxy A3(2017) as a test device. On the device is Android 8.0.0 the latest available version. 
Regardless which function of this library i use it turns the image 90°. On a newer Android device and on ios this does not happen. 

Is there a minimum android version for this library or can this be fixed?

**Comment by MParrao** [comment]
Hi,
 I'm facing the same issue on a Samsung S9+

**Comment by guhungry** [comment]
currently it is not support to change orientation by this library but may be need to set orientation in exif header.
The fix from this library is to maintain exif header only for orientation data from source and result image. (fixes need to be implemented in [android-photo-manipulator](https://github.com/guhungry/android-photo-manipulator))

**Comment by guhungry** [comment]
Hi @akrueger90, @MParrao can you test if version 1.2.5 fix your problem.

**Comment by akrueger90** [comment]
Hello, thank you for the update. Sadly it changes nothing on the behavior in my case

**Comment by guhungry** [comment]
Can you paste the image for me (upload somewhere) and copy the command you're using so i can reproduce?

**Comment by ansarikhurshid786** [comment]
I am also facing similar issue while adding overlay image. is there any update or workaround for this?

**Comment by guhungry** [comment]
> I am also facing similar issue while adding overlay image. is there any update or workaround for this?

Hi @ansarikhurshid786, can you upload original image some where so i can find the root cause. Suspect EXIF handling.

**Comment by guhungry** [comment]
I think I found the culprit https://github.com/guhungry/react-native-photo-manipulator/blob/09c0a4d7b7937120efb3265c4403e88d5b91095d/android/src/main/java/com/guhungry/rnphotomanipulator/utils/ImageUtils.kt#L21

Will test and fix asap.
Reference: https://stackoverflow.com/questions/45552108/is-it-possible-to-make-bitmapfactory-decodefile-respect-exif

**Comment by ansarikhurshid786** [comment]
Image for your reference: 
https://drive.google.com/file/d/13nYyR6hKaFefmX8deNAzftIfhGyblz6p/view?usp=sharing

**Comment by guhungry** [comment]
Should be fixed in v1.2.7 if you guys still have problem please reopen this issue, thanks.

**Comment by ansarikhurshid786** [comment]
Great, thanks alot.
