### ISSUE TITLE
rotate image in android

### ISSUE THREAD

**Issue by ansarikhurshid786** [guhungry/react-native-photo-manipulator#376]
Hi @guhungry 
I found an issue in samsung galaxy s8 plus. I used overlay method and it returning roated image

Snapcode: 
PhotoManipulator.overlayImage(assets.uri, tempImgPath, { y: assets.height - 70, x: 0 }, "image/png");

In android emulator working perfectly but and in one device.

**Comment by ansarikhurshid786** [comment]
it seem similar issue 
https://github.com/guhungry/react-native-photo-manipulator/issues/343

**Comment by guhungry** [comment]
Seems so, please continue in #343.
