### ISSUE TITLE
This change fixed Android app build. 

### ISSUE THREAD

**Issue by LeDanielH** [guhungry/react-native-photo-manipulator#512]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-photo-manipulator@1.2.7` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-photo-manipulator/android/src/main/java/com/guhungry/rnphotomanipulator/utils/ImageUtils.kt b/node_modules/react-native-photo-manipulator/android/src/main/java/com/guhungry/rnphotomanipulator/utils/ImageUtils.kt
index b72b2e8..b0e4c5e 100644
--- a/node_modules/react-native-photo-manipulator/android/src/main/java/com/guhungry/rnphotomanipulator/utils/ImageUtils.kt
+++ b/node_modules/react-native-photo-manipulator/android/src/main/java/com/guhungry/rnphotomanipulator/utils/ImageUtils.kt
@@ -47,7 +47,7 @@ object ImageUtils {
             // Do nothing.
         }
 
-        val resource = name.lowercase(Locale.getDefault()).replace("-", "_")
+        val resource = name.toLowerCase(Locale.getDefault()).replace("-", "_")
         return context.resources.getIdentifier(resource, "drawable", context.packageName)
     }
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by guhungry** [comment]
@LeDanielH Thanks for the report.

After I review kotlin document .lowercase() was added in version 1.5 and .toLowerCase() was also deprecated in this version too. [Kotlin Document](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/to-lower-case.html)
So if you compiled with kotlin version < 1.5 it couldn't be compile and would need patch package. 

So I won't fix this.
