### ISSUE TITLE
RNPhotoManipulator.batch not working

### ISSUE THREAD

**Issue by tdinckaya** [guhungry/react-native-photo-manipulator#528]
TypeError: operations.map is not a function. (In 'operations.map(ParamUtils.toBatchNative)', 'operations.map' is undefined)

batch
    PhotoManipulator.js:9:84
TouchableOpacity.props.onPress
    Result.tsx:92:14
Pressability$argument_0.onPress
    TouchableOpacity.js:174:10
_performTransitionSideEffects
    Pressability.js:655:17
_receiveSignal
    Pressability.js:589:6
responderEventHandlers.onResponderRelease
    Pressability.js:499:8
invokeGuardedCallbackImpl
    ReactNativeRenderer-dev.js:286:4
invokeGuardedCallback
    ReactNativeRenderer-dev.js:497:2
invokeGuardedCallbackAndCatchFirstError
    ReactNativeRenderer-dev.js:521:2
executeDispatch
    ReactNativeRenderer-dev.js:683:41
executeDispatchesInOrder
    ReactNativeRenderer-dev.js:707:19
executeDispatchesAndRelease
    ReactNativeRenderer-dev.js:872:28
forEach
    [native code]:0
forEachAccumulated
    ReactNativeRenderer-dev.js:851:4
runEventsInBatch
    ReactNativeRenderer-dev.js:897:20
runExtractedPluginEventsInBatch
    ReactNativeRenderer-dev.js:1069:18
batchedUpdates$argument_0
    ReactNativeRenderer-dev.js:2835:35
batchedUpdates$1
    ReactNativeRenderer-dev.js:20569:13
batchedUpdates
    ReactNativeRenderer-dev.js:2731:29
_receiveRootNodeIDEvent
    ReactNativeRenderer-dev.js:2834:16
receiveTouches
    ReactNativeRenderer-dev.js:2911:27
__callFunction
    MessageQueue.js:425:19
__guard$argument_0
    MessageQueue.js:112:6
__guard
    MessageQueue.js:373:10
callFunctionReturnFlushedQueue
    MessageQueue.js:111:4
callFunctionReturnFlushedQueue
    [native code]:0

**Comment by philippe28** [comment]
I found the same error followed the example, however the order of the bash function is wrong the correct one is
 (image, operations, cropRegion, targetSize, quality, mimeType)

**Comment by guhungry** [comment]
@philippe28 Thanks, I updated README accordingly.
