### ISSUE TITLE
Overlay not working in high resolution image

### ISSUE THREAD

**Issue by brijesh-livebird** [guhungry/react-native-photo-manipulator#576]
i have image that resolution is 1000 * 1500 and when i apply 
and overlay image Width is 186*118 
i want overlay that image in bottom right position and i apply this calculation for that 
and its working if my image is low resolution like 300 or 500 but not working in big resolution 

position = {
                  x: image.width - (overlayWidth + 10),
                  y: image.height - (overlayHeight + 10),
                };
i attach screen shot that i add Test with rotation with red text (that is image format) as overlay with that above condition and i recive output like this 

![Screenshot_2022-05-13-13-00-25-791_com sharecatalog](https://user-images.githubusercontent.com/53654434/168234560-78c5fa32-4001-41b5-b7cd-ed78f399a0df.jpg)

@guhungry @rumwerfer

**Comment by guhungry** [comment]
Hi @brijesh-livebird, sorry for the super late reply. I tested on both iOS and Android with version 1.5.0.
I used overlay() and it worked just fine. Which operation did you use at the time?

iOS
![ios](https://github.com/guhungry/react-native-photo-manipulator/assets/4032276/286d47f4-22d2-492f-89a5-942ba329bd9a)

Android
![android](https://github.com/guhungry/react-native-photo-manipulator/assets/4032276/6467897a-95ce-4878-b0f6-2ef50cd3ba09)

**Comment by guhungry** [comment]
If you still have a problem please reopen this issue. I'll close it for now.
