### ISSUE TITLE
Build IOS Failed v.1.2.7

### ISSUE THREAD

**Issue by dnx-xy** [guhungry/react-native-photo-manipulator#599]
iOS build failed with LD error with react-native link react-native-photo-manipulator.
Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target 'react-native-photo-manipulator' from project 'Pods')

With manual installation on IOS error compileC
RTCConvert.h not found.

RN 0.69.1

**Comment by AllStackDev1** [comment]
Did you find a solution to this?

**Comment by guhungry** [comment]
Hi @dnx-xy and @AllStackDev1,

For react native >= 60, you can just add a dependency via
```
$ yarn add react-native-photo-manipulator
```
(or)
```
$ npm install react-native-photo-manipulator
```

and run `pod install` in ios before build should work

If you still encountered problem please reopen this issue
