### ISSUE TITLE
not working in iOS .

### ISSUE THREAD

**Issue by KashifEno8** [guhungry/react-native-photo-manipulator#671]
when I run from the Xcode build fails has occurred and when I fix that issue and update the pod file then the app is run properly but the crop does not happen at all and when I add the library and update the build phase then another error has occurred below is the image for reference.
<img width="344" alt="Screenshot 2022-12-01 at 3 32 09 PM" src="https://user-images.githubusercontent.com/96740223/205024221-fd58ccd2-7720-45a3-99f2-2dcfb911a368.png">

**Comment by guhungry** [comment]
@KashifEno8 Can I have more info? What is your React Native version?
If you add this library correctly it should automatically linked in Podfile.lock
```
  - react-native-photo-manipulator (1.2.7):
    - React
    - WCPhotoManipulator (~> 2.0.4)
```

**Comment by guhungry** [comment]
Hi @KashifEno8, if you still have problem please feel free to reopen this issue.
