### ISSUE TITLE
Merge Images

### ISSUE THREAD

**Issue by cristea2017** [guhungry/react-native-photo-manipulator#69]
Please add image merge like this :

![image](https://user-images.githubusercontent.com/28201006/89396859-c3f42b00-d717-11ea-8946-8532d94ad369.png)

Thanks !

**Comment by guhungry** [comment]
Things to consider
1) What if image have different dimension when merge? (Bigger, Smaller)
2) How about different merge direction? (Down, Right)

**Comment by cristea2017** [comment]
> Things to consider
> 
> 1. What if image have different dimension when merge? (Bigger, Smaller)
> 2. How about different merge direction? (Down, Right)
> 3. What is appropriate api for merge image?
> 
> Available solutions: https://stackoverflow.com/questions/47132321/combining-two-image-into-one-new-image-in-react-native


1.Choose the biggest one
2. Vertically/horizontally
3. Take a look at this  :
[https://pinetools.com/merge-images](url)

can this be achived  ?

**Comment by cristea2017** [comment]
In my case i want to to merge vertically 2 or more images to create  animated blocks in minecraft follow this link : 
[https://guide.bedrock.dev/-/blocks-flipbooks](url)

use this package : [https://www.npmjs.com/package/react-native-images-merge](url)
