### ISSUE TITLE
please set compileSdkVersion to 30 or above

### ISSUE THREAD

**Issue by isinuyk** [guhungry/react-native-photo-manipulator#720]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tasks'.
> Could not create task ':react-native-image-manipulator:compileDebugJavaWithJavac'.
   > In order to compile Java 9+ source, please set compileSdkVersion to 30 or above
   
  RN: 0.72.6

**Comment by jamshed-ali-oip** [comment]
i am already using 33 version
but its not working

**Comment by isinuyk** [comment]
@jamshed-ali-oip you don't need to change it in your android/build.gradle
instead, you'll need to change this value inside of the build.gradle of this library in your node_modules

Personally, I created a patch for this BUT it would be nice to have this fix in the library itself.

**Comment by guhungry** [comment]
@isinuyk @jamshed-ali-oip Sorry for late reply though.

With build.gradle in this project get value from gradle.properties
<img width="519" alt="Screenshot 2566-11-10 at 21 08 47" src="https://github.com/guhungry/react-native-photo-manipulator/assets/4032276/a9c958b1-fac3-40cf-ab91-03c86d8f6ae8">
https://github.com/guhungry/react-native-photo-manipulator/blob/master/android/build.gradle#L30-L34

Could you try to set compileSdkVersion in your root android project as in example project?
<img width="307" alt="Screenshot 2566-11-10 at 21 14 33" src="https://github.com/guhungry/react-native-photo-manipulator/assets/4032276/f758356c-81ad-4f3c-8814-9a71082d9f5c">

https://github.com/guhungry/react-native-photo-manipulator/blob/master/example/android/build.gradle#L6-L8

**Comment by isinuyk** [comment]
@guhungry yep, this is actually what I did. I just updated the compileVersion to 30 and it worked for me.

**Comment by guhungry** [comment]
@isinuyk, it was fixed in [v1.2.8](https://github.com/guhungry/react-native-photo-manipulator/releases/tag/v1.2.8)
