### ISSUE TITLE
Feat : Is it possible to rotate image ?

### ISSUE THREAD

**Issue by sairajKalkundre** [guhungry/react-native-photo-manipulator#803]
It would be great to have a rotate function that accepts angle and rotates the image accordingly.

**Comment by tomerh2001** [comment]
Also joining the question. I'll create a PR if it's relevant

**Comment by guhungry** [comment]
> It would be great to have a rotate function that accepts angle and rotates the image accordingly.

Hi @sairajKalkundre, which rotation angles should it support any or just basic ones (90, 180, 270)?

> Also joining the question. I'll create a PR if it's relevant

Hi @tomerh2001, PRs are welcome, firstly need to implement this feature in native api in [ios-photo-manipulator](/guhungry/ios-photo-manipulator) and [android-photo-manipulator](/guhungry/android-photo-manipulator), and then expose api in this library.

**Comment by sairajKalkundre** [comment]
@guhungry Yeah just the basic ones. @tomerh2001 It would be awesome.

**Comment by guhungry** [comment]
Hi @sairajKalkundre, @tomerh2001
This feature was released in [v1.5.0](https://github.com/guhungry/react-native-photo-manipulator/releases/tag/v1.5.0) 🎉 🎉 🎉 🎉 🎉 🎉
