### ISSUE TITLE
Does it work with images that are in base64?

### ISSUE THREAD

**Issue by williamingenews** [guhungry/react-native-photo-manipulator#804]
I am trying to use the library but I have a question, can I perform a printText() with an image that is in base64 or should the use of a public uri be mandatory to make the change?

**Comment by guhungry** [comment]
Not directly support yet. Currently this library only support images imported from react native,  local file or network file only.

For workaround you can save base64 string to file first using react-native-fs.

**Comment by williamingenews** [comment]
Thanks

**Comment by guhungry** [comment]
Hi @williamingenews,
Base64 encoded images support has been added in [v1.7.0](https://github.com/guhungry/react-native-photo-manipulator/releases/tag/v1.7.0)
