### ISSUE TITLE
String too big

### ISSUE THREAD

**Issue by aliza-khu** [guhungry/react-native-photo-manipulator#832]
I am getting the below error while capturing such an image and trying to convert the image to base64.
Error: String too big at Obj_set_any (native) at setAny
![IMG_1403](https://github.com/guhungry/react-native-photo-manipulator/assets/112606371/f2b1b6eb-f801-4a7d-ab0f-36cfc15b205c)

**Comment by guhungry** [comment]
This library does not support using base64 images directly. Please save to file first and supply path in to this library.

https://github.com/guhungry/react-native-photo-manipulator/issues/804#issuecomment-2050886922

**Comment by aliza-khu** [comment]
@guhungry, This is fixed now and is not related to the react-native-photo-manipulator. ref: https://github.com/thegrizzlylabs/geniusscan-sdk-demo/issues/87#issuecomment-2179820356
