### ISSUE TITLE
y must be >= 0

### ISSUE THREAD

**Issue by aliza-khu** [guhungry/react-native-photo-manipulator#837]
RNPhotoManipulator.crop(image, cropRegion, targetSize, MimeType.PNG)

The above method returning error y must be >= 0. I also noticed that the issue was raised in specific Android devices listed below:

SM-F731U
SM-F936U
Pixel 8 Pro
Pixel 7 Pro

**Comment by guhungry** [comment]
Hi @aliza-khu, Can you give me full parameter values (cropRegion, targetSize) and also source image

**Comment by aliza-khu** [comment]
@guhungry, Here are the details:

react-native-photo-manipulator: 1.5.0
Android Version: 14
----------------------------------------
cropRegion: {"x":0,"y":0,"height":4025,"width":3060}
image: file:///storage/emulated/0/Android/data/com.reclym.org/files/8684a4dd-6fae-4b57-bbe7-27cf17e65800.jpeg
imageType: image/png,
targetSize: {"height":4025,"width":3060}

Device Name: Samsung M33 5G
Model Name: SM-M336BU/DS

Here
![8684a4dd-6fae-4b57-bbe7-27cf17e65800](https://github.com/guhungry/react-native-photo-manipulator/assets/112606371/d7fc3563-dd68-41e1-b21f-10250dccfb08)
 is the file:

**Comment by guhungry** [comment]
Thanks, i will try to debug it tonight. i suspect that it relates to screen density or something around that.
I will try to fix it asap

**Comment by guhungry** [comment]
Hi @aliza-khu, it was fixed in [v1.5.1](https://github.com/guhungry/react-native-photo-manipulator/releases/tag/v1.5.1)

**Comment by aliza-khu** [comment]
@guhungry, Till now after being on V1.5.1 under basic testing it seems like the issue is fixed. 👍 
Thank You. I will let you know if anything comes up!
