### ISSUE TITLE
v1.5.1 is missing the lib folder

### ISSUE THREAD

**Issue by elrony** [guhungry/react-native-photo-manipulator#844]
Hello,

The latest release 1.5.1 is missing the lib folder.

Thanks

**Comment by guhungry** [comment]
Thank you for your report it was due to https://github.com/guhungry/react-native-photo-manipulator/pull/833 which update Github Actions dependencies and it has breaking change [here](https://github.com/js-devtools/npm-publish?tab=readme-ov-file#v2-behavior-changes)

**Comment by guhungry** [comment]
Hi @elrony, it was fixed in [v1.5.2](https://github.com/guhungry/react-native-photo-manipulator/releases/tag/v1.5.2) 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by elrony** [comment]
Thanks for fixing this quickly and for your work on the library! ♥️
