### ISSUE TITLE
was resolved to 1.5.3, which depends on WCPhotoManipulator (~> 2.3.0)

### ISSUE THREAD

**Issue by ansarikhurshid786** [guhungry/react-native-photo-manipulator#859]
I am upgrading to latest version and getting following error 
was resolved to 1.5.3, which depends on
      WCPhotoManipulator (~> 2.3.0)
      
Version details
"react-native-photo-manipulator": "1.5.3",
"react-native": "0.64.4",

**Comment by guhungry** [comment]
Can you try delete `Podfile.lock` and run `pod update`?

**Comment by ansarikhurshid786** [comment]
I already tried and getting same error.

**Comment by guhungry** [comment]
Can you paste full error log when you run command line?

**Comment by guhungry** [comment]
Hello @ansarikhurshid786, does the problem still occur?

**Comment by zzz08900** [comment]
The problem still exists. I just upgraded to 1.6.0 and the following error：
```[!] CocoaPods could not find compatible versions for pod "WCPhotoManipulator":
  In snapshot (Podfile.lock):
    WCPhotoManipulator (= 2.1.1, ~> 2.1.1)

  In Podfile:
    react-native-photo-manipulator (from `../node_modules/react-native-photo-manipulator`) was resolved to 1.6.0, which depends on
      WCPhotoManipulator (~> 2.3.0)

Specs satisfying the `WCPhotoManipulator (= 2.1.1, ~> 2.1.1), WCPhotoManipulator (~> 2.3.0)` dependency were found, but they required a higher minimum deployment target.
```

RN version is 0.74.3
The minimum deployment target is iOS 13.4 (RN 0.74 default)

**Comment by zzz08900** [comment]
I just tried deleting Podfile.lock and re-install, now the error message is
```
[!] CocoaPods could not find compatible versions for pod "WCPhotoManipulator":
  In Podfile:
    react-native-photo-manipulator (from `../node_modules/react-native-photo-manipulator`) was resolved to 1.6.0, which depends on
      WCPhotoManipulator (~> 2.3.0)

None of your spec sources contain a spec satisfying the dependency: `WCPhotoManipulator (~> 2.3.0)`.
```

**Comment by zzz08900** [comment]
Hm, so we need to update repo with `pod repo update` or CocoaPods cannot find version 2.3.0 for WCPhotoManipulator

**Comment by guhungry** [comment]
> Hm, so we need to update repo with `pod repo update` or CocoaPods cannot find version 2.3.0 for WCPhotoManipulator
@zzz08900 
Yes, run `pod install --repo-update` or `pod repo update && pod install` should do.

does it work for you now?

**Comment by zzz08900** [comment]
Version 1.6.0 works now. Much appreciated.

**Comment by guhungry** [comment]
> Version 1.6.0 works now. Much appreciated.

@zzz08900 thanks, for conform that it works. ❤️ 


> Yes, run `pod install --repo-update` or `pod repo update && pod install` should do.


@ansarikhurshid786, can you try these command if it still not work please reopen this issue though.
