### ISSUE TITLE
version 1.7.0 - XCode issue 'react_native_photo_manipulator-Swift.h' file not found

### ISSUE THREAD

**Issue by elrony** [guhungry/react-native-photo-manipulator#919]
Hello,

I have recently upgraded the library to v.1.7.0 and the following error pops up when building the iOS app:

<img width="949" alt="image" src="https://github.com/user-attachments/assets/b661193e-f3a9-4b85-94bc-c115692f14a1">

1.6.2 works fine.

Thanks

**Comment by guhungry** [comment]
Ok, i’ll recheck asap. But, have you tried `pod repo update && pod update`

**Comment by elrony** [comment]
Hello!

Yes I did try resetting pods.

I have deleted the Pod cache `rm -rf ~/Library/Caches/CocoaPods` and the Xcode derived data
I have deleted node_modules, upgraded the rpm module to 1.7.0 and ran `npm i`
Then in the ios folder I ran `bundle exec pod deintegrate;rm Podfile.lock;bundle exec pod install --repo-update`

I have also tried to run the commands that you suggested through the bundle tool, but I am still getting the same error.

I do not know if it matters but my app is a bare workflow, react native app with the latest version of RN 0.75.2.

Thanks a lot for looking into this!

**Comment by peterchijioke** [comment]
'react_native_photo_manipulator-Swift.h' file not found, I am facing same issue.

**Comment by JustynRoseRocket** [comment]
also facing the same issue here currently running `react-native: 0.72.15` after upgrading to `react-native-photo-manipulator:1.7.0`

**Comment by guhungry** [comment]
I need to revert the change to use objective c instead of swift in ParamUtils and ImageUtils since swift is not compatible when new architecture is enabled

**Comment by guhungry** [comment]
Hi @elrony @peterchijioke @JustynRoseRocket,

It should be addressed in v1.7.2. But, if you still find the issue please do not hesitate to reopen this issue.
