### ISSUE TITLE
RNPhotoManipulatorSpec.h file not found when updating to React Native 0.75.2

### ISSUE THREAD

**Issue by fercebas** [guhungry/react-native-photo-manipulator#942]
Hello everyone,

I’m experiencing an issue after refactoring an old project to use newer React Native dependencies. We utilize react-native-photo-manipulator for one of our features. While it worked fine in our previous implementation, updating the dependencies has led to a build error.

**Error Details:**
- Location: node_modules/react-native-photo-manipulator/ios/RNPhotoManipulator.h:3:9
- Error Message: `'RNPhotoManipulatorSpec.h' file not found`

**Environment:**
- React Native: 0.75.2
- react-native-photo-manipulator: ^1.7.3

**Pod Installation Command Used:**
`RCT_NEW_ARCH_ENABLED=1 pod install`

**Steps I’ve Taken:**
1. Deleted node_modules, yarn.lock, and the ios/Pods folder along with Podfile.lock.
2. Ran pod repo update && pod update.
3. Deleted the DerivedData folder.

Despite these attempts, the issue persists. Occasionally, I receive a different error about there being too many symbols, but the 'RNPhotoManipulatorSpec.h' file not found error is the most consistent.

---------

Has anyone else encountered this problem? Do you have any insights into what might be causing it?

I’m more than willing to provide additional information if needed. Any help would be greatly appreciated!

Note: I’ve attached an image of the error message for reference.

![image](https://github.com/user-attachments/assets/156b1010-b7d7-414c-b0c0-73594dbfdfbf)

**Comment by guhungry** [comment]
Hi @fercebas,

Thanks for your report. I'm working on it with this solution https://github.com/callstack/react-native-builder-bob/issues/637 in [Fix/ios-codegen-doesnt-work](https://github.com/guhungry/react-native-photo-manipulator/tree/Fix/ios-codegen-doesnt-work)

**Comment by fercebas** [comment]
That's awesome, will follow back to test again once it's done.

Thank you, @guhungry!

Awesome work with this repository, I've seen it getting constant updates lately.

**Comment by guhungry** [comment]
Hi @fercebas, it should be fixed in [v1.7.4](https://github.com/guhungry/react-native-photo-manipulator/releases/tag/v1.7.4)

**Comment by fercebas** [comment]
Thank you, @guhungry!

Are you planning to upload it to NPM?
