### ISSUE TITLE
arabic support

### ISSUE THREAD

**Issue by ansarikhurshid786** [guhungry/react-native-photo-manipulator#943]
I am trying to append text over which will have depend on app language. 

it is not supporting arabic(right to left)

**Comment by ansarikhurshid786** [comment]
@guhungry can you help me

**Comment by guhungry** [comment]
Is the issue as described here https://stackoverflow.com/questions/12121591/android-canvas-drawtext-from-right-to-left.
I may need to add new parameter textDirection for text, it should be doable but i can’t a specific timeline though.

**Comment by ansarikhurshid786** [comment]
@guhungry can add support arabic(rtl) textDirection. it will really helpful

**Comment by guhungry** [comment]
Hi @ ansarikhurshid786, which platform has a problem android or iOS?

**Comment by ansarikhurshid786** [comment]
@guhungry I have problem in both platform. I m trying with get width of arabic text and according placing but it is still proper align. can you give me best work around ?

**Comment by ansarikhurshid786** [comment]
@guhungry any reference to support arabic content(rtl).

**Comment by guhungry** [comment]
@ansarikhurshid786 For a workaround, I'm unsure if you can use a reversed string (.split('').reverse().join('')) and then align it right.

**Comment by ansarikhurshid786** [comment]
@guhungry text already reversed. problem is placement. i am trying text length minus(using react native text size library for better) work fine if arabic text only but when text consist of number, comma, alpha number so calculation is not correct. i have big string in table format so not look good at all.

**Comment by ansarikhurshid786** [comment]
@guhungry can you add support textDirection or any better option ?

**Comment by ansarikhurshid786** [comment]
@guhungry any plan to support rtl direction?

**Comment by ansarikhurshid786** [comment]
@guhungry i have fix my self and PR https://github.com/guhungry/react-native-photo-manipulator/pull/950#issue-2599864076

**Comment by ansarikhurshid786** [comment]
@guhungry i am trying to install it from git repo. not working. 
was successfully found. However, this package itself specifies a main module field that could not be resolved

**Comment by guhungry** [comment]
Hi @ansarikhurshid786, I implemented text alignment in ios-photo-manipulator to support rigit and left alignment. 

Here I draw text at same x (middle of image) for all test strings with rotation effect. After I publish it should be easily updated to use in this library

<img width="993" alt="Screenshot 2567-10-23 at 14 59 51" src="https://github.com/user-attachments/assets/33aeea3a-98f1-4b9d-9039-e4fdd94b1dee">

**Comment by guhungry** [comment]
Sure I plan to finish it tonight, my timezone is UTC+7

**Comment by ansarikhurshid786** [comment]
@guhungry thank u and appriciate. yes i know u located in thailand

**Comment by guhungry** [comment]
Hi @ansarikhurshid786, Does this text display correctly? (I can't read Arabic)

```TypeScript
function texts(): TextOptions[] {
  return [
    {
      text: 'اَلْعَرَبِيَّةُ',
      color: 'red',
      textSize: 500,
      position: { x: 80, y: 300 },
      thickness: 30,
      shadowRadius: 10,
      shadowOffset: { x: 5, y: 10 },
      shadowColor: 'green',
    },
    {
      text: 'اَلْعَرَبِيَّةُ',
      color: 'blue',
      textSize: 500,
      position: { x: 80, y: 300 },
    }
  ]
}
```

iOS:
<img width="314" alt="Screenshot 2567-10-23 at 17 25 52" src="https://github.com/user-attachments/assets/19e485d0-a766-486e-8829-f30c9d6da31f">


Android:
<img width="324" alt="Screenshot 2567-10-23 at 17 26 04" src="https://github.com/user-attachments/assets/7ec5d62d-7c67-4d6e-9d28-b748e2b1f295">

**Comment by ansarikhurshid786** [comment]
Arabic start from right and english start from left

**Comment by ansarikhurshid786** [comment]
@guhungry please dont merge my change and don't refer it(PR). I checked that is wrong.

**Comment by guhungry** [comment]
Hi @ansarikhurshid786, can you test with this beta version 1.8.0-rc.0

**Comment by ansarikhurshid786** [comment]
@guhungry first of thank u support. let me check and confirm u. currenlty u added for ios only right.

**Comment by ansarikhurshid786** [comment]
still publishing in process

**Comment by guhungry** [comment]
Both Android and iOS. For Android, I used your change minus containArabic(), since it works without this function during my test.

**Comment by ansarikhurshid786** [comment]
@guhungry it is working better but if arabic consist of non arabic then not working properly. better add params textDirection: 'rtl' or 'left'

**Comment by ansarikhurshid786** [comment]
@guhungry thank u for support. please try early

**Comment by guhungry** [comment]
@ansarikhurshid786 can you try [1.8.0-rc.1](https://www.npmjs.com/package/react-native-photo-manipulator/v/1.8.0-rc.1).

Here is my example code

```TypeScript
import { TextDirection } from 'react-native-photo-manipulator';
...
    let options : TextOptions[] = [
      {
        text: 'Test Print Text 2',
        color: 'green',
        textSize: 300,
        position: { x: 180, y: 1550 },
      },
      {
        text: 'Test Print Text 3',
        color: 'pink',
        textSize: 30,
        position: { x: 280, y: 1200 },
        rotation: 30,
        direction: TextDirection.LTR,
      },
      {
        text: 'اَلْعَرَبِيَّةُ',
        color: 'blue',
        textSize: 500,
        position: { x: 80, y: 300 },
        direction: TextDirection.RTL,
      },
    ];
```

**Comment by ansarikhurshid786** [comment]
direction is not available. I am getting while typing itself. 
TypeError: Cannot read property 'RTL' of undefined

**Comment by ansarikhurshid786** [comment]
oh i m using 1.8.0-rc.0
"react-native-photo-manipulator": "1.8.0-rc.0"

i will update and try now.

**Comment by ansarikhurshid786** [comment]
Perfect. I have tested in iOS. Thanks alot

**Comment by guhungry** [comment]
> @guhungry I am trying in android auto linking is not working and manualy giving error. Previously i was using react-native.photo.manipulator: 1.2.7 was working fine..
> 
> react-native:0.64.4 react-native.photo.manipulator: 1.8.0

Wow! The React Native version is quite outdated. I'll attempt to reproduce it.

**Comment by ansarikhurshid786** [comment]
Yes, I want to update but there is so many dependencies.

**Comment by ansarikhurshid786** [comment]
[@](https://github.com/JimmyDaddy/react-native-image-marker/issues/83)
