### ISSUE TITLE
Type mismatch: inferred type is Bitmap.Config? but Bitmap.Config was expected

### ISSUE THREAD

**Issue by panna-oo** [guhungry/react-native-photo-manipulator#956]
Hi , I just upgrade RN from 0.74.2 to 0.76.0 and i also upgrade react-native-photo-manipulator from 1.2.7 to 1.8.0 .
I run yarn android but failed，and the log shows ../node_modules/react-native-photo-manipulator/android/src/main/java/com/guhungry/rnphotomanipulator/utils/ImageUtils.kt:82:29 Type mismatch: inferred type is Bitmap.Config? but Bitmap.Config was expected

**Comment by guhungry** [comment]
Ok, I can reproduce this error, I'll fix it asap.

**Comment by valery-lavrik** [comment]
Good afternoon! I also just ran into this problem. I really look forward to your help!

**Comment by guhungry** [comment]
@panna-oo @valery-lavrik, the fix was released in [v1.8.1](https://www.npmjs.com/package/react-native-photo-manipulator/v/1.8.1)

**Comment by panna-oo** [comment]
@guhungry  Thank you so much !!!
