### ISSUE TITLE
Not support for react native 0.64.* - Android

### ISSUE THREAD

**Issue by ansarikhurshid786** [guhungry/react-native-photo-manipulator#959]
I have update react-native-photo-manipulato from 1.27. to 1.8.1 for rtl support. iOS is working perfectly. 
Auto linking is not working in android and mannual linking also not working. 

Can u support react native 0.64* or is any dependency require to use latest version, if such mentioned minimum react native version in documentation. 

I am using below version in my project and can't update now. I will plan to upgrade react native which require test all case. 
"react": "17.0.1",
"react-native": "0.64.4"

**Comment by guhungry** [comment]
Hi @ansarikhurshid786, I found the culprit; it was due to the code below.
https://github.com/guhungry/react-native-photo-manipulator/blob/115cd5654eaa3eeaa2ff71abafa76ea4387fd198/react-native.config.js#L8 If I comment out this line, React Native's autolink works fine.
As a short-term solution, I suggest using [patch-package](https://www.npmjs.com/package/patch-package).

### Before Comment
```
root@codespaces-8138ad:/workspaces/Rn64# yarn react-native link react-native-photo-manipulator
yarn run v1.22.5
$ /workspaces/Rn64/node_modules/.bin/react-native link react-native-photo-manipulator
warn Package react-native-photo-manipulator has been ignored because it contains invalid configuration. Reason: "dependency.platforms.android.cmakeListsPath" is not allowed
warn Calling react-native link [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.
Autolinking documentation: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
error Unknown dependency. Make sure that the package you are trying to link is already installed in your "node_modules" and present in your "package.json" dependencies.
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### After Comment
```
root@codespaces-8138ad:/workspaces/Rn64# yarn react-native link react-native-photo-manipulator
yarn run v1.22.5
$ /workspaces/Rn64/node_modules/.bin/react-native link react-native-photo-manipulator
warn Calling react-native link [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.
Autolinking documentation: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Linking "react-native-photo-manipulator" Android dependency
info Android module "react-native-photo-manipulator" has been successfully linked
Done in 0.40s.
```

**Comment by ansarikhurshid786** [comment]
@guhungry ok i will try patch-package and try till i upgrade.

**Comment by ansarikhurshid786** [comment]
@guhungry I am trying patch package. I am getting different eror 
Failed to create Jar file /Users/{unsername}/.gradle/caches/jars-8/b62cbf925325e7c95c4b128f2d052999/sdklib-31.5.2.jar

I tried to update gradle plugin and gradle version update but getting different error. 

Can you suggest something. I can't upgrade gradle version.

**Comment by ansarikhurshid786** [comment]
@guhungry finally i can able run in android. 
i have update my project react native from 0.64.4 to 0.65.3 along with gradle and gradle plugin 7+.
